version: '2'
services:
  app:
    build: ./backend
    restart: always
    depends_on:
      - db
      - jaeger
      - redis
    ports:
      - 9000:9000
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=devcamp
    ports:
      - 9001:5432
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
  jaeger:
    image: jaegertracing/all-in-one:1.22
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
  prometheus:
    image: prom/prometheus:v2.27.1
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana-data:/var/lib/grafana
      - ./monitoring/grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=admin
  redis:
    image: redis:alpine