version: '2'
services:
  app:
    build: ./backend
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - 9000:9000
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=devcamp
    ports:
      - 9001:5432
    volumes:
      - ./db/db-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379